language: node_js

node_js:
- 6

cache:
  directories:
    - node_modules

script:
  - npm test && npm run codecov

notifications:
  email: false

before_deploy:
  - npm run publish

deploy:
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
